AWSTemplateFormatVersion: 2010-09-09
Parameters:
  envlevel:
    Type: String
    AllowedValues:
      - dev.
      - test.
      - PROD
  theregion:
    Type: String
    Default: ap-southeast-2
Conditions: 
  IsProd: !Equals [ !Ref envlevel, PROD ]
Resources:
  wwwbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], api.aekos.org.au]]
      WebsiteConfiguration:
        IndexDocument: index.html
  wwwdns:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # the CloudFront zone
        DNSName: !GetAtt cfdistro.DomainName
      HostedZoneName: api.aekos.org.au.
      Name: !Join ['', [www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], api.aekos.org.au, .]]
      Type: A
  cfdistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Join ['', [www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], api.aekos.org.au]]
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Join ['', [S3-www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], api.aekos.org.au]]
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          -
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !Join ['', [www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], api.aekos.org.au, .s3.amazonaws.com]]
            Id: !Join ['', [S3-www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], api.aekos.org.au]]
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:521175994262:certificate/68c6f36a-094a-4269-87e7-3ffc31ce3f68
          SslSupportMethod: sni-only
