service: aekos-api-serverless

package:
  exclude:
    - secrets.yml

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 30
  vpc:
    securityGroupIds:
      - "${file(secrets.yml):${self:custom.stage}.securityGroupId}"
    subnetIds:
      - "${file(secrets.yml):${self:custom.stage}.subnet1Id}"
      - "${file(secrets.yml):${self:custom.stage}.subnet2Id}"
  environment:
    # FIXME get these encrypted
    # DBURL: "${self:custom.secrets.DBURL}"
    DBURL: "${file(secrets.yml):${self:custom.stage}.DBURL}"
    # DBPORT: "${self:custom.secrets.DBPORT}"
    DBPORT: "${file(secrets.yml):${self:custom.stage}.DBPORT}"
    # DBNAME: "${self:custom.secrets.DBNAME}"
    DBNAME: "${file(secrets.yml):${self:custom.stage}.DBNAME}"
    # DBUSER: "${self:custom.secrets.DBUSER}"
    DBUSER: "${file(secrets.yml):${self:custom.stage}.DBUSER}"
    # DBPASS: "${self:custom.secrets.DBPASS}"
    DBPASS: "${file(secrets.yml):${self:custom.stage}.DBPASS}"

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):$self:custom.stage} # FIXME get this working

functions:
  v10-getTraitVocab-json:
    handler: v10-getTraitVocab-json.handler
    events:
      - http:
          path: v1/getTraitVocab.json
          method: get
          cors: true
  v10-getEnvironmentalVariableVocab-json:
    handler: v10-getEnvironmentalVariableVocab-json.handler
    events:
      - http:
          path: v1/getEnvironmentalVariableVocab.json
          method: get
          cors: true
  v10-speciesAutocomplete-json:
    handler: v10-speciesAutocomplete-json.handler
    events:
      - http:
          path: v1/speciesAutocomplete.json
          method: get
          cors: true
  v10-speciesSummary-json:
    handler: v10-speciesSummary-json.handler
    events:
      - http:
          path: v1/speciesSummary.json
          method: get
          cors: true
