# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: aekos-api-serverless

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10

functions:
  v10-getTraitVocab-json:
    handler: v10-getTraitVocab-json.handler
    events:
      - http:
          path: v1/getTraitVocab.json
          method: get
          cors: true
  v10-getEnvironmentalVariableVocab-json:
    handler: v10-getEnvironmentalVariableVocab-json.handler
    events:
      - http:
          path: v1/getEnvironmentalVariableVocab.json
          method: get
          cors: true
