service: aekos-api-serverless

package:
  exclude:
    - secrets.yml

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 30
  vpc:
    securityGroupIds:
      - "${file(secrets.yml):${self:custom.stage}.securityGroupId}"
    subnetIds:
      - "${file(secrets.yml):${self:custom.stage}.subnet1Id}"
      - "${file(secrets.yml):${self:custom.stage}.subnet2Id}"
  environment:
    # FIXME get these encrypted
    # DBURL: "${self:custom.secrets.DBURL}"
    DBURL: "${file(secrets.yml):${self:custom.stage}.DBURL}"
    # DBPORT: "${self:custom.secrets.DBPORT}"
    DBPORT: "${file(secrets.yml):${self:custom.stage}.DBPORT}"
    # DBNAME: "${self:custom.secrets.DBNAME}"
    DBNAME: "${file(secrets.yml):${self:custom.stage}.DBNAME}"
    # DBUSER: "${self:custom.secrets.DBUSER}"
    DBUSER: "${file(secrets.yml):${self:custom.stage}.DBUSER}"
    # DBPASS: "${self:custom.secrets.DBPASS}"
    DBPASS: "${file(secrets.yml):${self:custom.stage}.DBPASS}"

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):$self:custom.stage} # FIXME get this working
  documentation:
    # FIXME doesn't write to the format that AWS expects: {info: {description: "", version: "", title: "", contact: {name: "", email: ""}}}
    api:
      version: '1'
      summary: 'AEKOS API'
      description: |
        The AEKOS API is used for Machine2Machine (M2M) REST access to AEKOS ecological data.
        <h1>High level workflow</h1>
        <ul>
          <li>Start with a trait or species</li>
          <li>Find what species have that trait or what traits/environmental variables are available for that species</li>
          <li>Use your traits/species/environmental variables to retrieve the data with the retrieval services</li>
        </ul>
    models:
      -
        name: "SpeciesSummaryList"
        contentType: "application/json"
        schema:
          type: array
          items:
            -
              # id: "/items"
              properties:
                id:
                  # id: "/properties/id"
                  type: string
                recordsHeld:
                  # id: "/properties/recordsHeld"
                  type: integer
                  format: int32
                speciesName:
                  # id: "/properties/speciesName"
                  type: string
              type: "object"

plugins:
  - serverless-aws-documentation

functions:
  v10-getTraitVocab-json:
    handler: v10-getTraitVocab-json.handler
    events:
      - http:
          path: v1/getTraitVocab.json
          method: get
          cors: true
  v10-getEnvironmentalVariableVocab-json:
    handler: v10-getEnvironmentalVariableVocab-json.handler
    events:
      - http:
          path: v1/getEnvironmentalVariableVocab.json
          method: get
          cors: true
  v10-speciesAutocomplete-json:
    handler: v10-speciesAutocomplete-json.handler
    events:
      - http:
          path: v1/speciesAutocomplete.json
          method: get
          cors: true
          documentation:
            summary: "Autocomplete partial species names"
            description: |
              Performs an autocomplete on the partial species name supplied. Results starting with the supplied
              fragment will be returned ordered by most relevant.
            queryParams:
              -
                name: "q"
                description: "partial species name"
  v10-speciesSummary-json:
    handler: v10-speciesSummary-json.handler
    events:
      - http:
          path: v1/speciesSummary.json
          method: get
          cors: true
          documentation:
            summary: "Get a summary of the specified species names"
            description: |
              A summary of the information that the system holds on the supplied species name(s) including a count
              of records. If the system doesn't have any data on a species name, no record for the species name will
              be in the result.
            queryParams:
              -
                name: "speciesNames"
                description: "list of species names"
            methodResponses:
              -
                statusCode: 200
                responseModels:
                  "application/json": "SpeciesSummaryList"
